"""
Live WhatsApp Test - send_with_review mode (safe, won't auto-send)

This opens WhatsApp Web with a message ready. YOU click Send.
"""

import sys
sys.path.insert(0, '.')

from backend.utils.whatsapp_client import WhatsAppClient

phone = "+17326160491"
message = """🍵 Tea Stall Bench - Live Test!

This message was generated by our AI agent pipeline.

If you're reading this, the WhatsApp integration works! 🎉

- Writer Agent: ✅
- Publisher Agent: ✅  
- WhatsApp Client: ✅
"""

print("=" * 50)
print("🍵 Tea Stall Bench - Live WhatsApp Test")
print("=" * 50)
print(f"📱 Phone: {phone}")
print(f"📝 Message: {len(message)} chars")
print(f"🔒 Mode: Manual Review (YOU click Send)")
print("=" * 50)
print("\n⏳ Opening WhatsApp Web in 10 seconds...")
print("   A browser tab will open with the message ready.")
print("   YOU decide whether to click Send.\n")

client = WhatsAppClient()

try:
    result = client.send_with_review(phone, message)
    print(f"\n✅ Result: {result}")
    print("\n👆 Check your browser - message should be ready to send!")
except Exception as e:
    print(f"\n❌ Error: {e}")
    print("\nTroubleshooting:")
    print("  1. Is WhatsApp Web logged in at web.whatsapp.com?")
    print("  2. Is your default browser open?")
    print("  3. Do you have pywhatkit installed? (pip install pywhatkit)")
